[project]
name = "proofstamp"
description = "Unique voting contract for project 02"
authors = ["solidworkssa"]
telemetry = false
cache_dir = ".cache"

[contracts.proofstamp]
path = "contracts/proofstamp.clar"

[repl.analysis]
passes = ["check_checker"]
